openapi: 3.1.0
info:
  title: API сервер для проекта «Шесть городов».
  description: Список ресурсов и маршрутов сервера «Шесть городов»
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 2.0.0
tags:
  - name: users
    description: Действия с пользователем
  - name: offers
    description: Действия с объявлениями
  - name: comments
    description: Действия с комментариями
paths:
  /users/register:
    post:
      tags:
        - users
      summary: Регистрация пользователя
      description: Регистрирует нового пользователя
      requestBody:
        $ref: '#/components/schemas/users/createUserRequest'
      responses:
        $ref: '#/components/schemas/users/createUserResponses'

  /users/login:
    post:
      tags:
        - users
      summary: Авторизация пользователя
      description: Авторизует пользователя на основе логина и пароля. Возвращает токен
      requestBody:
        $ref: '#/components/schemas/users/loginRequest'
      responses:
        $ref: '#/components/schemas/users/loginResponses'

  /users/logout:
    post:
      tags:
        - users
      summary: Выход
      description: Завершает пользовательский сеанс
      security:
        - Bearer: [ ]
      responses:
        $ref: '#/components/schemas/users/logoutResponses'

  /users/isAuthorized:
    get:
      tags:
        - users
      summary: Проверка состояния пользователя
      description: Возвращает состояния клиента — авторизован или нет
      security:
        - Bearer: [ ]
      responses:
        $ref: '#/components/schemas/users/isAuthorizedResponses'

  /offers/create:
    post:
      tags:
        - offers
      summary: Создание нового предложения
      description: Создаёт нового предложения
      security:
        - Bearer: []
      requestBody:
        $ref: '#/components/schemas/offers/createOfferRequest'
      responses:
        $ref: '#/components/schemas/offers/createOfferResponses'

  /offers/offer/{offerId}:
    get:
      tags:
        - offers
      summary: Детальная информация по предложению
      description: Возвращает детальную информацию по предложению
      parameters:
        - name: offerId
          in: query
          content:
            application/json:
              schema:
                type:
                  - string
      responses:
        $ref: '#/components/schemas/offers/offerResponses'

    patch:
      tags:
        - offers
      summary: Редактирование предложения
      description: Редактирует предложение
      parameters:
        - name: offerId
          in: query
          content:
            application/json:
              schema:
                type:
                  - string
      security:
        - Bearer: [ ]
      requestBody:
        $ref: '#/components/schemas/offers/editOfferRequest'
      responses:
        $ref: '#/components/schemas/offers/editOfferResponses'

    delete:
      tags:
        - offers
      summary: Удаление предложения
      description: Удаляет предложение
      parameters:
        - name: offerId
          in: query
          content:
            application/json:
              schema:
                type:
                  - string
      security:
        - Bearer: [ ]
      responses:
        $ref: '#/components/schemas/offers/deleteOfferResponses'

  /offers/:
    get:
      tags:
        - offers
      summary: Список предложений по аренде
      description: Возвращает список предложений по аренде. По умолчанию возвращает не больше 60 предложений. Предложения отсортированы по дате публикации (по убыванию)
      responses:
        $ref: '#/components/schemas/offers/offersResponses'

  /offers/premium/{city}:
    get:
      tags:
        - offers
      summary: Премиальные предложения для города
      description: Возвращает не больше трёх премиальных предложений для определённого города. Список возвращаемых предложений отсортирован по дате публикации (по убыванию)
      parameters:
        - name: city
          in: query
          content:
            application/json:
              schema:
                type:
                  - string
      responses:
        $ref: '#/components/schemas/offers/premiumResponses'

  /offers/favourites:
    get:
      tags:
        - offers
      summary: Список избранных предложений
      description: Возвращает список избранных предложений пользователя
      security:
        - Bearer: [ ]
      responses:
        $ref: '#/components/schemas/offers/favouritesResponses'

  /offers/favourite/{offerId}:
    post:
      tags:
        - offers
      summary: Добавление предложения в избранное
      description: Добавляет предложение в избранное
      security:
        - Bearer: [ ]
      parameters:
        - name: offerId
          in: query
          content:
            application/json:
              schema:
                type:
                  - string
      responses:
        $ref: '#/components/schemas/offers/addToFavouritesResponses'

    delete:
      tags:
        - offers
      summary: Удаление предложения из избранного
      description: Удаляет предложение из избранного
      security:
        - Bearer: [ ]
      parameters:
        - name: offerId
          in: query
          content:
            application/json:
              schema:
                type:
                  - string
      responses:
        $ref: '#/components/schemas/offers/deleteFromFavouritesResponses'

  /comments/{offerId}:
    get:
      tags:
        - comments
      summary: Список комментариев для предложения
      description: Возвращает список комментариев для определённого предложения
      parameters:
        - name: offerId
          in: query
          content:
            application/json:
              schema:
                type:
                  - string
      responses:
        $ref: '#/components/schemas/comments/commentsResponses'

  /comments/add/{offerId}:
    post:
      tags:
        - comments
      summary: Добавление комментария
      description: Добавляет комментарий к определённому предложению
      security:
        - Bearer: [ ]
      parameters:
        - name: offerId
          in: query
          content:
            application/json:
              schema:
                type:
                  - string
      responses:
        $ref: '#/components/schemas/comments/addCommentResponses'

components:
  securitySchemes:
    Bearer:
      name: TOKEN
      type: http
      scheme: bearer
      in: header
      description: Токен для проверки авторизации

  schemas:
    users:
      userType:
        type:
          - object

        properties:
          id:
            type:
              - string
            example: 6329c3d6a04ab1061c6425ea

          name:
            type:
              - string
            example: Даша Жукова

          email:
            type:
              - string
            example: keks@htmlacademy.ru

          avatarPath:
            type:
              - string

          type:
            type:
              - string
            example: Usual

      createUserRequest:
        description: Информация для создания нового пользователя
        content:
          application/json:
            schema:
              type:
                - object

              properties:
                name:
                  type:
                    - string
                  example: Даша Жукова

                email:
                  type:
                    - string
                  example: keks@htmlacademy.ru

                password:
                  type:
                    - string
                  example: 123456
        required: true

      createUserResponses:
        "201":
          description: Пользователь зарегистрирован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/users/userType'
        "400":
          description: Невалидные данные
        "409":
          description: Пользователь с таким email уже существует

      loginRequest:
        description: Информация для входа
        content:
          application/json:
            schema:
              type:
                - object

              properties:
                email:
                  type:
                    - string
                  example: keks@htmlacademy.ru

                password:
                  type:
                    - string
                  example: 123456
        required: true

      loginResponses:
        "200":
          description: Пользователь авторизирован
          content:
            application/json:
              schema:
                token:
                  type:
                    - string

        "404":
          description: Такого пользователя не существует

      logoutResponses:
        "200":
          description: Пользовательский сеанс завершён

        "401":
          description: Пользователь не авторизирован

      isAuthorizedResponses:
        "200":
          description: Пользователь авторизирован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/users/userType'

        "401":
          description: Пользователь не авторизирован

    offers:
      offerType:
        type:
          - object

        properties:
          id:
            type:
              - string
          title:
            type:
              - string
          description:
            type:
              - string
          publishDate:
            type:
              - string
          city:
            type:
              - string
          previewImage:
            type:
              - string
          images:
            type:
              - array
            items:
              type:
                - string
          isPremium:
            type:
              - boolean
          isFavourite:
            type:
              - boolean
          rating:
            type:
              - integer
          housingType:
            type:
              - string
          roomsNumber:
            type:
              - integer
          guestsNumber:
            type:
              - integer
          price:
            type:
              - integer
          facilities:
            type:
              - array
            items:
              type:
                - string
          author:
            type:
              - string
          commentsIds:
            type:
              - array
            items:
              type:
                - string
          commentsNumber:
            type:
              - integer
          coordinates:
            type:
              - string

      createOfferRequest:
        description: Данные для создания нового предложения
        content:
          application/json:
            schema:
              type:
                - object
              properties:
                title:
                  type:
                    - string
                description:
                  type:
                    - string
                publishDate:
                  type:
                    - string
                city:
                  type:
                    - string
                previewImage:
                  type:
                    - string
                images:
                  type:
                    - array
                  items:
                    type:
                      - string
                isPremium:
                  type:
                    - boolean
                isFavourite:
                  type:
                    - boolean
                rating:
                  type:
                    - integer
                housingType:
                  type:
                    - string
                roomsNumber:
                  type:
                    - integer
                guestsNumber:
                  type:
                    - integer
                price:
                  type:
                    - integer
                facilities:
                  type:
                    - array
                  items:
                    type:
                      - string
                author:
                  type:
                    - string
                commentsIds:
                  type:
                    - array
                  items:
                    type:
                      - string
                commentsNumber:
                  type:
                    - integer
                coordinates:
                  type:
                    - string
        required: true

      createOfferResponses:
        "201":
          description: Предложение создано
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/offers/offerType'
        "400":
          description: Невалидные данные
        "401":
          description: Пользователь не авторизирован

      editOfferRequest:
        description: Редактирует существующее предложение
        content:
          application/json:
            schema:
              type:
                - object
              properties:
                title:
                  type:
                    - string
                description:
                  type:
                    - string
                publishDate:
                  type:
                    - string
                city:
                  type:
                    - string
                previewImage:
                  type:
                    - string
                images:
                  type:
                    - array
                  items:
                    type:
                      - string
                isPremium:
                  type:
                    - boolean
                isFavourite:
                  type:
                    - boolean
                rating:
                  type:
                    - integer
                housingType:
                  type:
                    - string
                roomsNumber:
                  type:
                    - integer
                guestsNumber:
                  type:
                    - integer
                price:
                  type:
                    - integer
                facilities:
                  type:
                    - array
                  items:
                    type:
                      - string
                author:
                  type:
                    - string
                commentsIds:
                  type:
                    - array
                  items:
                    type:
                      - string
                commentsNumber:
                  type:
                    - integer
                coordinates:
                  type:
                    - string
        required: true

      offersList:
        type: array
        items:
          type: object
          $ref: '#/components/schemas/offers/offerType'

      editOfferResponses:
        "201":
          description: Предложение изменено
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/offers/offerType'
        "400":
          description: Невалидные данные
        "401":
          description: Пользователь не авторизирован
        "403":
          description: У текущего пользователя нет доступа к предложению
        "404":
          description: Предложение не найдено

      deleteOfferResponses:
        "200":
          description: Предложение удалено
        "400":
          description: Невалидные данные
        "401":
          description: Пользователь не авторизирован
        "403":
          description: У текущего пользователя нет доступа к предложению
        "404":
          description: Предложение не найдено

      offersResponses:
        "200":
          description: Список предложений по аренде
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/offers/offersList'

      offerResponses:
        "200":
          description: Детальная информация по предложению
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/offers/offerType'
        "404":
          description: Не найдено предложения с таким id

      premiumResponses:
        "200":
          description: Список премиальных предложений в городе
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/offers/offersList'
        "404":
          description: Не найдено премиальных предложений

      favouritesResponses:
        "200":
          description: Список избранных предложений пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/offers/offersList'
        "401":
          description: Пользователь не авторизирован
        "404":
          description: Не найдено избранных предложений

      addToFavouritesResponses:
        "200":
          description: Предложение добавлено в избранное
        "401":
          description: Пользователь не авторизирован
        "403":
          description: У текущего пользователя нет доступа к предложению
        "404":
          description: Не найдено предложения с таким id

      deleteFromFavouritesResponses:
        "200":
          description: Предложение удалено из избранного
        "401":
          description: Пользователь не авторизирован
        "403":
          description: У текущего пользователя нет доступа к предложению
        "404":
          description: Не найдено предложения с таким id

    comments:
      commentType:
        type:
          - object

        properties:
          id:
            type:
              - string
          text:
            type:
              - string
          publishDate:
            type:
              - string
          authorId:
            type:
              - string

      commentsList:
        type: array
        items:
          type: object
          $ref: '#/components/schemas/comments/commentType'


      commentsResponses:
        "200":
          description: Список предложений по аренде
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/comments/commentsList'
        "404":
          description: Не найдено предложения с таким id

      addCommentResponses:
        "200":
          description: Комменатрий добавлен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/comments/commentType'
        "400":
          description: Невалидный комментарий
        "401":
          description: Пользователь не авторизирован
        "404":
          description: Не найдено предложения с таким id
